-- ============================================================
-- VELORA PASS V1.9.2
-- Auditoría privada: quién creó cada voucher/cotización.
-- Ejecutar UNA VEZ en Supabase > SQL Editor.
-- ============================================================

create table if not exists public.record_audit (
  id bigint generated by default as identity primary key,
  record_type text not null check (record_type in ('voucher', 'quote')),
  record_id uuid not null,
  created_by uuid,
  created_by_email text,
  created_at timestamptz not null default now(),
  unique (record_type, record_id)
);

alter table public.record_audit enable row level security;

drop policy if exists "authenticated_read_record_audit" on public.record_audit;

create policy "authenticated_read_record_audit"
on public.record_audit
for select
to authenticated
using (true);

-- El registro se crea desde un trigger del servidor.
-- Ningún usuario del navegador necesita permiso INSERT sobre record_audit.
create or replace function public.capture_record_creator()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  creator_email text;
begin
  creator_email := auth.jwt() ->> 'email';

  insert into public.record_audit (
    record_type,
    record_id,
    created_by,
    created_by_email,
    created_at
  )
  values (
    TG_ARGV[0],
    NEW.id,
    auth.uid(),
    creator_email,
    coalesce(NEW.created_at, now())
  )
  on conflict (record_type, record_id) do nothing;

  return NEW;
end;
$$;

drop trigger if exists capture_voucher_creator on public.vouchers;
create trigger capture_voucher_creator
after insert on public.vouchers
for each row
execute function public.capture_record_creator('voucher');

drop trigger if exists capture_quote_creator on public.quotes;
create trigger capture_quote_creator
after insert on public.quotes
for each row
execute function public.capture_record_creator('quote');

-- Limpiar auditoría cuando se borra un registro.
create or replace function public.delete_record_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.record_audit
  where record_type = TG_ARGV[0]
    and record_id = OLD.id;

  return OLD;
end;
$$;

drop trigger if exists delete_voucher_audit on public.vouchers;
create trigger delete_voucher_audit
after delete on public.vouchers
for each row
execute function public.delete_record_audit('voucher');

drop trigger if exists delete_quote_audit on public.quotes;
create trigger delete_quote_audit
after delete on public.quotes
for each row
execute function public.delete_record_audit('quote');

-- Los registros creados ANTES de esta migración no tienen autor verificable.
-- Se insertan como históricos sin usuario para que el panel muestre "Sin registro".
insert into public.record_audit (record_type, record_id, created_at)
select 'voucher', v.id, v.created_at
from public.vouchers v
on conflict (record_type, record_id) do nothing;

insert into public.record_audit (record_type, record_id, created_at)
select 'quote', q.id, q.created_at
from public.quotes q
on conflict (record_type, record_id) do nothing;
